# pixels connector configurations
connector.name=pixels
# Retina config
# Set false to skip Retina buffer splits and read only flushed file splits.
retina.buffer.split.enable=true

# serverless config
# it can be on, off, auto, or session
cloud.function.switch=auto
clean.intermediate.result=true
